export const GET_ALL_ORDER_LOADING = "GET_ALL_ORDER_LOADING"
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS"
export const GET_ALL_ORDER_ERROR = "GET_ALL_ORDER_ERROR"


export const GET_ALL_TIMESLOT_LOADING = "GET_ALL_TIMESLOT_LOADING"
export const GET_ALL_TIMESLOT_SUCCESS = "GET_ALL_TIMESLOT_SUCCESS"
export const GET_ALL_TIMESLOT_ERROR = "GET_ALL_TIMESLOT_ERROR"
