export const ATTENDANCE_API_LOADING = "ATTENDANCE_API_LOADING"
export const ATTENDANCE_API_ERROR = "ATTENDANCE_API_ERROR"
export const ATTENDANCE_API_SUCCESS = "ATTENDANCE_API_SUCCESS"

export const SERATTENDANCE_API_LOADING = "SERATTENDANCE_API_LOADING"
export const SERATTENDANCE_API_ERROR = "SERATTENDANCE_API_ERROR"
export const SERATTENDANCE_API_SUCCESS = "SERATTENDANCE_API_SUCCESS"


export const REPORT_ATTENDANCE_API_LOADING = "REPORT_ATTENDANCE_API_LOADING"
export const REPORT_ATTENDANCE_API_ERROR = "REPORT_ATTENDANCE_API_ERROR"
export const REPORT_ATTENDANCE_API_SUCCESS = "REPORT_ATTENDANCE_API_SUCCESS"


export const SERVICE_REPORT_ATTENDANCE_API_LOADING = "SERVICE_REPORT_ATTENDANCE_API_LOADING"
export const SERVICE_REPORT_ATTENDANCE_API_ERROR = "SERVICE_REPORT_ATTENDANCE_API_ERROR"
export const SERVICE_REPORT_ATTENDANCE_API_SUCCESS = "SERVICE_REPORT_ATTENDANCE_API_SUCCESS"