export const AVAILABILITY_API_LOADING = "AVAILABILITY_API_LOADING"
export const AVAILABILITY_API_ERROR = "AVAILABILITY_API_ERROR"
export const AVAILABILITY_API_SUCCESS = "AVAILABILITY_API_SUCCESS"


export const SUPERVISOR_AVAILABILITY_API_LOADING = "SUPERVISOR_AVAILABILITY_API_LOADING"
export const SUPERVISOR_AVAILABILITY_API_ERROR = "SUPERVISOR_AVAILABILITY_API_ERROR"
export const SUPERVISOR_AVAILABILITY_API_SUCCESS = "SUPERVISOR_AVAILABILITY_API_SUCCESS"

