export const SERVICE_API_SUCCESS = "SERVICE_API_SUCCESS";
export const SERVICE_API_LOADING = "SERVICE_API_LOADING";
export const SERVICE_API_ERROR = "SERVICE_API_ERROR";


// get all services 
export const SERVICES_GET_API_LOADING = "SERVICES_GET_API_LOADING";
export const SERVICES_GET_API_SUCCESS = "SERVICES_GET_API_SUCCESS";
export const SERVICES_GET_API_ERROR = "SERVICES_GET_API_ERROR";

// Delete the service  
export const SERVICES_DELETE_API_LOADING = "SERVICES_DELETE_API_LOADING";
export const SERVICES_DELETE_API_SUCCESS = "SERVICES_DELETE_API_SUCCESS";
export const SERVICES_DELETE_API_ERROR = "SERVICES_DELETE_API_ERROR";


// get all plan 

export const PLAN_GET_API_LOADING = "PLAN_GET_API_LOADING";
export const PLAN_GET_API_SUCCESS = "PLAN_GET_API_SUCCESS";
export const PLAN_GET_API_ERROR = "PLAN_GET_API_ERROR";


export const TICKET_GET_API_LOADING = "TICKET_GET_API_LOADING";
export const TICKET_GET_API_SUCCESS = "TICKET_GET_API_SUCCESS";
export const TICKET_GET_API_ERROR = "TICKET_GET_API_ERROR";


export const TICKET_HEAD_GET_API_LOADING = "TICKET_HEAD_GET_API_LOADING";
export const TICKET_HEAD_GET_API_SUCCESS = "TICKET_HEAD_GET_API_SUCCESS";
export const TICKET_HEAD_GET_API_ERROR = "TICKET_HEAD_GET_API_ERROR";