export const GET_ALL_CUSTOMER_LOADING = "GET_ALL_CUSTOMER_LOADING"
export const GET_ALL_CUSTOMER_SUCCESS = "GET_ALL_CUSTOMER_SUCCESS"
export const GET_ALL_CUSTOMER_ERROR = "GET_ALL_CUSTOMER_ERROR"

export const GET_ALL_CUSTOMER_FILTER_BY_FLOW_LOADING = "GET_ALL_CUSTOMER_FILTER_BY_FLOW_LOADING"
export const GET_ALL_CUSTOMER_FILTER_BY_FLOW_SUCCESS = "GET_ALL_CUSTOMER_FILTER_BY_FLOW_SUCCESS"
export const GET_ALL_CUSTOMER_FILTER_BY_FLOW_ERROR = "GET_ALL_CUSTOMER_FILTER_BY_FLOW_ERROR"
// get delte the customer 

export const GET_CUSTOMER_DELETE_LOADING = 'GET_CUSTOMER_DELETE_LOADING';
export const GET_CUSTOMER_DELETE_SUCCESS = 'GET_CUSTOMER_DELETE_SUCCESS';
export const GET_CUSTOMER_DELETE_ERROR = 'GET_CUSTOMER_DELETE_ERROR';


// get customer update
export const GET_CUSTOMER_UPDATE_LOADING = 'GET_CUSTOMER_UPDATE_LOADING';
export const GET_CUSTOMER_UPDATE_SUCCESS = 'GET_CUSTOMER_UPDATE_SUCCESS';
export const GET_CUSTOMER_UPDATE_ERROR = 'GET_CUSTOMER_UPDATE_ERROR' ;


export const GET_CUSTOMER_CREATE_LOADING = 'GET_CUSTOMER_UPDATE_LOADING'
export const GET_CUSTOMER_CREATE_SUCCESS='GET_CUSTOMER_CREATE_SUCCESS'
export const GET_CUSTOMER_CREATE_ERROR='GET_CUSTOMER_CREATE_ERROR'


export const GET_ALL_Enquiry_LOADING = "GET_ALL_Enquiry_LOADING"
export const GET_ALL_Enquiry_SUCCESS = "GET_ALL_Enquiry_SUCCESS"
export const GET_ALL_Enquiry_ERROR = "GET_ALL_Enquiry_ERROR"



export const GET_ALL_Members_LOADING = "GET_ALL_Members_LOADING"
export const GET_ALL_Members_SUCCESS = "GET_ALL_Members_SUCCESS"
export const GET_ALL_Members_ERROR = "GET_ALL_Members_ERROR"


export const GET_ALL_LASTSERVICES_LOADING = "GET_ALL_LASTSERVICES_LOADING"
export const GET_ALL_LASTSERVICES_SUCCESS = "GET_ALL_LASTSERVICES_SUCCESS"
export const GET_ALL_LASTSERVICES_ERROR = "GET_ALL_LASTSERVICES_ERROR"

// Filter customers
export const FILTER_CUSTOMERS_LOADING = "FILTER_CUSTOMERS_LOADING"
export const FILTER_CUSTOMERS_SUCCESS = "FILTER_CUSTOMERS_SUCCESS"
export const FILTER_CUSTOMERS_ERROR = "FILTER_CUSTOMERS_ERROR"

// Reminder constants
export const GET_ALL_REMINDER_LOADING = "GET_ALL_REMINDER_LOADING"
export const GET_ALL_REMINDER_SUCCESS = "GET_ALL_REMINDER_SUCCESS"
export const GET_ALL_REMINDER_ERROR = "GET_ALL_REMINDER_ERROR"

export const GET_REMINDER_BY_ID_LOADING = "GET_REMINDER_BY_ID_LOADING"
export const GET_REMINDER_BY_ID_SUCCESS = "GET_REMINDER_BY_ID_SUCCESS"
export const GET_REMINDER_BY_ID_ERROR = "GET_REMINDER_BY_ID_ERROR"

export const SET_REMINDER_LOADING = "SET_REMINDER_LOADING"
export const SET_REMINDER_SUCCESS = "SET_REMINDER_SUCCESS"
export const SET_REMINDER_ERROR = "SET_REMINDER_ERROR"


